### ISSUE TITLE
Missing Flexx

### ISSUE THREAD

**Issue by louisabraham** [ericsnowcurrently/pyweb#1]
Not really an issue, but I stumbled over this repo while googling, and posting an issue is the most convenient way to comment on github.

You might have missed [PScript](https://github.com/flexxui/pscript) (formerly flexx/PyScript) which is actively developed and quite fast. Take a look at https://github.com/flexxui/flexx/wiki/PyScript-vs-X

**Comment by ericsnowcurrently** [comment]
Yep, I didn't have a lot of time to search exhaustively for possible solutions (active or otherwise).  Thanks for the heads up.  I'll add PScript/Flexx.

**Comment by louisabraham** [comment]
You welcome :)

The current solutions are really a mess to index and compare and your repo will be truly useful!

Do you plan on doing some benchmarks? I would be happy to help!

**Comment by ericsnowcurrently** [comment]
Yep, there's a lot of prior art out there.  I've re-organized the info I've collected thus far.  Most of the info has moved into the wiki.

I wasn't thinking about benchmarks at this point.  However, it would probably make sense. :)  Help is definitely welcome!  Feel free to open a separate issue for that.

**Comment by ericsnowcurrently** [comment]
I've added PScript to the list of prior art.
